sonar.projectKey=bhattumang7-github-io
sonar.projectName=bhattumang7.github.io
sonar.host.url=http://localhost:9010

sonar.sources=pages,scripts,_includes,_posts,_data
sonar.tests=scripts/tests
sonar.exclusions=**/vendor/**,**/*.min.js,scripts/tests/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
